import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// Served from the custom domain (secure.creditvana.com) at the root by default.
// Set VITE_BASE_PATH=/creditvana-frontend/ to deploy to a GitHub project page.
const base = process.env.VITE_BASE_PATH || '/'

/**
 * GitHub Pages has no SPA rewrite, so a deep link like /report returns 404.
 * This emits a 404.html that bounces the request to index.html with the
 * original path encoded in the query string; a snippet in index.html restores
 * it via the History API. The number of path segments to preserve is derived
 * from `base` so the two can never drift apart.
 */
function githubPagesSpaFallback(): Plugin {
  let resolvedBase = base

  return {
    name: 'github-pages-spa-fallback',
    configResolved(config) {
      resolvedBase = config.base
    },
    generateBundle() {
      const segmentsToKeep = resolvedBase.split('/').filter(Boolean).length

      this.emitFile({
        type: 'asset',
        fileName: '404.html',
        source: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>CreditVana</title>
    <script>
      // Generated by vite.config.ts – do not edit by hand.
      var pathSegmentsToKeep = ${segmentsToKeep};
      var l = window.location;
      l.replace(
        l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
        l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
        l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
        (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
        l.hash
      );
    </script>
  </head>
  <body></body>
</html>
`,
      })
    },
  }
}

export default defineConfig({
  base,
  plugins: [react(), tailwindcss(), githubPagesSpaFallback()],
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
    },
  },
})
